"""Write tak/TakUpdateRoots.h: the root CAs the gateway trusts when it downloads updates from GitHub.

github.com chains to USERTrust ECC (Sectigo); release downloads come from *.githubusercontent.com,
which chains to ISRG Root X1 (Let's Encrypt). The rest are fallbacks in case GitHub changes CA.

    pip install certifi
    python examples/tak_gateway/tools/make_update_roots.py
"""
import os
import re

import certifi

ROOTS = [
    "USERTrust ECC Certification Authority",
    "USERTrust RSA Certification Authority",
    "Sectigo Public Server Authentication Root E46",
    "Sectigo Public Server Authentication Root R46",
    "ISRG Root X1",
    "ISRG Root X2",
    "DigiCert Global Root G2",
    "DigiCert Global Root CA",
]

GW = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(GW, "tak", "TakUpdateRoots.h")

bundle = open(certifi.where(), encoding="utf-8").read()
certs = dict(re.findall(r'# Label: "([^"]+)"\n(?:#[^\n]*\n)*(-----BEGIN CERTIFICATE-----\n.*?-----END CERTIFICATE-----)', bundle, re.S))

parts, missing = [], []
for name in ROOTS:
    pem = certs.get(name)
    if pem:
        parts.append("// " + name + "\n" + "\n".join('"%s\\n"' % line for line in pem.splitlines()))
    else:
        missing.append(name)

with open(OUT, "w", encoding="utf-8", newline="\n") as f:
    f.write("// Generated by tools/make_update_roots.py from the certifi CA bundle. Do not edit.\n")
    f.write("#pragma once\n\nstatic const char TAK_UPDATE_ROOTS[] =\n")
    f.write("\n".join(parts))
    f.write(";\n")

print("wrote %s with %d roots" % (OUT, len(parts)))
if missing:
    print("not in certifi (skipped): " + ", ".join(missing))
