"""Firmware version YY.MMDD.HHMM in UTC (Zulu).

Clean checkout: time of the last commit, so a local build and the GitHub release of the same
code carry the same version. Uncommitted changes: time of the build, so every modified build
gets a new number. TAK_GW_VERSION in the environment overrides both (used by the release job).

PlatformIO pre-script (writes tak/TakVersion.h), or run directly to print the version.
"""
import datetime
import os
import subprocess
import time

if __name__ == "__main__":
    GW = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
else:
    Import("env")  # noqa: F821 (PlatformIO / SCons builtin; scripts run there without __file__)
    GW = os.path.join(env["PROJECT_DIR"], "examples", "tak_gateway")  # noqa: F821
HEADER = os.path.join(GW, "tak", "TakVersion.h")


def _git(*args):
    return subprocess.run(["git", *args], cwd=GW, capture_output=True, text=True, check=True).stdout.strip()


def compute():
    forced = os.environ.get("TAK_GW_VERSION", "").strip()
    if forced:
        return forced, "env"
    try:
        dirty = _git("status", "--porcelain", "--untracked-files=no")
        stamp, source = (time.time(), "build time, uncommitted changes") if dirty else (int(_git("log", "-1", "--format=%ct")), "last commit")
    except (OSError, subprocess.CalledProcessError, ValueError):
        stamp, source = time.time(), "build time, no git"
    return datetime.datetime.fromtimestamp(stamp, datetime.timezone.utc).strftime("%y.%m%d.%H%M"), source


def write_header(ver):
    text = '#pragma once\n// Generated by tools/version.py at build time. Do not edit or commit.\n#define TAK_GW_VERSION "%s"\n' % ver
    try:
        if open(HEADER, encoding="utf-8").read() == text:
            return
    except OSError:
        pass
    with open(HEADER, "w", encoding="utf-8", newline="\n") as f:
        f.write(text)


if __name__ == "__main__":
    print(compute()[0])
else:
    v, why = compute()
    write_header(v)
    print("TAK gateway version %s (%s)" % (v, why))
